Add Naming and Code Organization guidelines
solitontech/CSharp pull request #1
Opened 2023-07-03 23:10 UTC by GowthamKarunakaran

This PR contains
- The consolidated guidelines for
         - Naming Convention
         - Code Organization
- Basic guidelines for
         - Documentation
         - Language Features

Signed-off-by: gowtham.karunakaran@solitontech.com

[link](https://solitontech.sharepoint.com/:x:/r/sites/CSharpCommunityOrganizers/Shared%20Documents/Enforce%20Standards/Enforce%20Standards%20Tracker%20-%20C%23%20Community.xlsx?d=we6fbd10596484d0e9c2c15d864c07a70&csf=1&web=1&e=B6Ouwp) to the Guidelines Trackers sheet FYR.

2023-07-04 04:05 UTC, keerthivarman-nageshwaran commented on Readme.md
> +    - Prefer using const if it's value is going to be changed in the run time.
Is this statement correct?

2023-07-12 05:06 UTC, GowthamKarunakaran commented on Readme.md
> +    - Prefer using const if it's value is going to be changed in the run time.
> Is this statement correct?
Sorry, It was a mistake. I have updated the guideline now.
Thanks for pointing out.

2023-07-12 08:49 UTC, ramganesh-soliton requested changes

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +Welcome to Soliton's C# coding conventions V1.0.0.0.
I think we can remove the versioning aspect, We can treat what is latest on the `main` as of the source of truth and latest.

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +1. [Naming](#naming)
suggestion: Use can use [[TOC]] to auto-populate table of contents in MD file

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +This contains the coding conventions/style guides for all C# code we develop. This document is constantly evolving. New rules might be added over time.
We can avoid these processes and implementation details out of this doc. The eventual audience for this file will be a set of engineers, devs, and interns who want to understand what is recommended in this.

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +- Casing:
Please use `prettier format` on this document to format this table better. You can setup prettier to be run on all saves in VS code

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +- Identifiers must start with a ***letter*** or underscore (***_***).
Is underscore allowed only for private fields? May be we should be explicit about that

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +# Soliton C# Style Guide
Consider a more appropriate file name... ReadMe doesn't sound right

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +- Identifiers must start with a ***letter*** or underscore (***_***).
For each of these conventions, we could give some numbering as well so that we can refer it and be explicit in conversations

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +    - **P**ascal**C**ase:
Can we make this a single table

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +- Choose names that are more meaningful and follow similar patterns for similar data types/ files.
These should be sub-sections under the Naming section, please update it accordingly with relevant md header styling

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +    - **Boolean** – Start with helping verbs.
nit: Use quote highlight inside of bolds

> some example

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +    - **Boolean** – Start with helping verbs.
Easier to read and skim through

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +    - **List** – Use collective name with a suffix as ‘**List**’.
I feel suffix addition is redundant and can be prone to error if we can change the dataype in future but don't update the variable name, I think we should instead ask for it to be avoided.

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +    - Consider adding base class names as suffix for the derived class where it would be helpful for readability.
Are we having some distinctions b/w some styles that are mandatory and others to be considered?

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +    - Consider adding base class names as suffix for the derived class where it would be helpful for readability.
Are conventions starting with `Consider` optional?

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +    - Consider using file name same as the name of the class in the file. In general, prefer one core class per file.
This should be mandatory and not `consider`

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +
Please add an example with code snippet

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +    - In VisualStudio, type forward slash('/') three times as '***///***'. The xml documentation syntax will be added.
This can be a tip in quote at the end of this section

2023-07-12 08:49 UTC, ramganesh-soliton commented on Readme.md
> +### General Guidelines
I think this section should be removed, these talk about clean code and should be separate doc

2023-07-12 08:51 UTC, ramganesh-soliton commented
I glanced through and have suggested a few things to structure this doc. I didn't look at the recommendation itself yet

2023-07-12 09:17 UTC, GowthamKarunakaran commented on Readme.md
> +1. [Naming](#naming)
With default Visual Studio (or) in github web, [[TOC]] is not getting auto-populated.
 When searched on online, it seems for auto-populating, we might be need to install a new VS extension (or) run a script.
[link for reference](https://stackoverflow.com/questions/11948245/markdown-to-create-pages-and-table-of-contents).
Please confirm. Also, could you share which extension you were using?

2023-07-15 06:03 UTC, viknesh-ramm commented on Readme.md
> +- Identifiers must start with a ***letter*** or underscore (***_***).
I think `_` is allowed only for private variables, at least in NI, which we can follow. I too agree we should be explicit about it

2023-07-15 07:00 UTC, viknesh-ramm reviewed
I have completed initial review.

2023-07-15 07:00 UTC, viknesh-ramm commented on Readme.md
> +          | Solution, Projects | `SolitonBank.sln , SolitonBankModel.cs` |
```suggestion
          | Solution, Projects, Files | `SolitonBank.sln , SolitonBank.csproj, SolitonBankModel.cs` |
```

2023-07-15 07:00 UTC, viknesh-ramm commented on Readme.md
> +    - **List** – Use collective name with a suffix as ‘**List**’.
Exactly. In clean code it is recommended to avoid [Avoid Disinformation](https://www.freecodecamp.org/news/clean-coding-for-beginners/ )

2023-07-15 07:00 UTC, viknesh-ramm commented on Readme.md
> +          | Private, Protected, Internal and Protected internal fields | `public class Employee { private double _houseRentAllowance  = 10000; .. }`  |
Are we sure that protected and internal variables should be in `_camelCase`? I think we need to double check

2023-07-15 07:00 UTC, viknesh-ramm commented on Readme.md
> +          | Local variables, Parameters | `public static double CalculateSalary(string ***basicPay***) { double **grossSalary** = basicPay + HRA; ..}` |
I think you may not be able to bold using *** when we enclose the line with ``. I think we can remove the bold to avoid the confusion

2023-07-15 07:00 UTC, viknesh-ramm commented on Readme.md
> +            - Example: Under the namespace 'Soliton.Bank.Model.Employee'. Use different names for the class instead of 'Employee', such as 'EmployeeData'.
I think this example is not correct. We should avoid using [noise words](https://www.freecodecamp.org/news/clean-coding-for-beginners/) like `Data` in the class names. I think we need to change the folder name rather than changing the class name.

2023-07-15 07:00 UTC, viknesh-ramm commented on Readme.md
> +      - “**Constants.cs**” to store the constant values that are used across multiple c# files.
This is a controversial suggestion. I have seen NI reviewers discouraging to use class names like `Utilities` and ask us to be more specific like `TestUtilities`. @ramganesh-soliton what do you think? I feel we need to suggest to avoid using common names like `Constants`, 'Utilities` and have more specific names.
cc: @keerthee3

2023-07-15 07:00 UTC, viknesh-ramm commented on Readme.md
> +    - **Get**EmployeeStatus()
Ideally we should use one word per concept i.e either Get or Fetch to retrieve some values. To avoid confusion, can we have a better example

2023-07-15 07:00 UTC, viknesh-ramm commented on Readme.md
> +    - Use ***readonly*** for the fields if it's value is going to be assigned either during the compile time or run time.
`run time` is generic terminology. Ideally we can assign `readonly` only from constructor. So we could say "during object initialization"

2023-07-15 07:00 UTC, viknesh-ramm commented on Readme.md
> +    - Use ***out*** for return parameters, that are not also an input.
Ideally we should avoid using out parameters and use it in functions like `bool TryGetValue(out var value)`. Can we add this as a suggestion?

2023-07-16 08:00 UTC, ramganesh-soliton commented on Readme.md
> +      - “**Constants.cs**” to store the constant values that are used across multiple c# files.
Yes I agree, All files and class names should have a purpose and be named accordingly. Using Utilities or constant can become a place where we dump everything

2023-07-16 08:02 UTC, ramganesh-soliton commented on Readme.md
> +1. [Naming](#naming)
In VS Code (in local machine) you can use extension to view the TOC, I believe GitHub should render it automatically (at least in AzDo it does render automatically) If it doesn't we can add back TOC

2023-07-17 07:28 UTC, GowthamKarunakaran commented on Readme.md
> +Welcome to Soliton's C# coding conventions V1.0.0.0.
Sure, Ram. The main branch will always have latest changes.
I thought versioning might be easy in future,
- If the solitons (users) wishes to keep track of the version of style guide they have implemented in their project.
- If we plan to add other items into this same repo, (say, C# Reusables). There might be updates to main branch but not as part of Style Guide. Still they can verify whether any changes happened to style guide or not.
                      -  But in case of version number. It might be more convenient to identify and easy to discuss any changes between the updates of the style guide.

I would also like to hear the thoughts of @keerthee3 , @viknesh-ramm , @keerthivarman-nageshwaran  and @sreeranjani

2023-07-18 06:28 UTC, GowthamKarunakaran commented on Readme.md
> +# Soliton C# Style Guide
- If we use a different file name other than 'Readme.md', github does not show the preview of Readme file's contents on the home page of the repo. Instead, it just shows the file name as a normal coding file with the contents hidden. 
- [Reference Link](https://stackoverflow.com/questions/69188881/rename-readme-md-to-custom-name-and-use-as-a-project-description) 
- Github expects the file to be named as 'README' for showing its content as below:
![image](https://github.com/solitontech/CSharp/assets/115445688/1edf31c2-bb82-492a-a75f-2dd0707662b2)

2023-07-18 08:32 UTC, ramganesh-soliton commented on Readme.md
> +# Soliton C# Style Guide
Ah! If this repo is just to maintain the style guide we can leave it as `ReadMe` for now and decide to move it later as a new sub-repo if required

cc: @keerthee3

2023-08-09 06:59 UTC, GowthamKarunakaran commented on Readme.md
> +Welcome to Soliton's C# coding conventions V1.0.0.0.
Removed the version info.

2023-08-09 07:01 UTC, GowthamKarunakaran commented on Readme.md
> +- Casing:
Thanks for the suggestion. Started using "Prettier - Code formatter" extension in VS Code

2023-08-09 07:02 UTC, GowthamKarunakaran commented on Readme.md
> +This contains the coding conventions/style guides for all C# code we develop. This document is constantly evolving. New rules might be added over time.
Sure, will remove this disclaimer later once we completed.

2023-08-09 07:05 UTC, GowthamKarunakaran commented on Readme.md
> +- Identifiers must start with a ***letter*** or underscore (***_***).
Added numbering to uniquely identify a guideline. I have used below format '{Starting Letter Of the Section}.Guideline.SubPoints'. Please let me know if there is any comments.

2023-08-09 07:06 UTC, GowthamKarunakaran commented on Readme.md
> +    - **P**ascal**C**ase:
Moved these into a table.

2023-08-09 07:08 UTC, GowthamKarunakaran commented on Readme.md
> +- Choose names that are more meaningful and follow similar patterns for similar data types/ files.
Added numbering. Hence, sub sections might not be needed I guess. Please let me know if you have any further comments

2023-08-09 07:10 UTC, GowthamKarunakaran commented on Readme.md
> +    - Consider adding base class names as suffix for the derived class where it would be helpful for readability.
Yes. Ram.
We use the terms ```Consider``` and ```Avoid``` for optional items. Remaining guidelines are mandatory by default.

2023-08-09 07:10 UTC, GowthamKarunakaran commented on Readme.md
> +    - Consider using file name same as the name of the class in the file. In general, prefer one core class per file.
Updated.

2023-08-09 07:11 UTC, GowthamKarunakaran commented on Readme.md
> +### General Guidelines
Removed this section.

2023-08-09 07:12 UTC, GowthamKarunakaran commented on Readme.md
> +          | Solution, Projects | `SolitonBank.sln , SolitonBankModel.cs` |
Updated the examples for casing.

2023-08-09 07:12 UTC, GowthamKarunakaran commented on Readme.md
> +          | Local variables, Parameters | `public static double CalculateSalary(string ***basicPay***) { double **grossSalary** = basicPay + HRA; ..}` |
Updated.

2023-08-09 07:16 UTC, GowthamKarunakaran commented on Readme.md
> +            - Example: Under the namespace 'Soliton.Bank.Model.Employee'. Use different names for the class instead of 'Employee', such as 'EmployeeData'.
1. Removed the example ```EmployeeData``` and updated with ```EmployeeSalary / EmployeePerformance```.
2. ```I think we need to change the folder name rather than changing the class name.``` - Here, do you mean the Namespace name?

2023-08-09 07:17 UTC, GowthamKarunakaran commented on Readme.md
> +    - **Get**EmployeeStatus()
Added some explanation for those examples. Please let me know if you have any further comments.

2023-08-09 07:18 UTC, GowthamKarunakaran commented on Readme.md
> +    - Use ***readonly*** for the fields if it's value is going to be assigned either during the compile time or run time.
Updated with "during object initialization"
```- Use readonly for the fields if it's value is going to be assigned either during the object initialization.```

2023-08-15 16:06 UTC, GowthamKarunakaran commented on Readme.md
> +    - **Boolean** – Start with helping verbs.
Updated the examples with quote highlights

2023-08-15 16:07 UTC, GowthamKarunakaran commented on Readme.md
> +    - **List** – Use collective name with a suffix as ‘**List**’.
- Updated the guideline as discussed

2023-08-15 16:09 UTC, GowthamKarunakaran commented on Readme.md
> +      - “**Constants.cs**” to store the constant values that are used across multiple c# files.
Updated the guideline as discussed

2023-08-15 16:10 UTC, GowthamKarunakaran commented on Readme.md
> +    - Use ***out*** for return parameters, that are not also an input.
Updated the guideline

2023-08-15 17:08 UTC, GowthamKarunakaran commented on Readme.md
> +
I will plan to take this item in a separate branch

2023-08-15 17:13 UTC, GowthamKarunakaran commented on Readme.md
> +          | Private, Protected, Internal and Protected internal fields | `public class Employee { private double _houseRentAllowance  = 10000; .. }`  |
Updated naming convention for the fields as mentioned below based on referring Microsoft guideline.
		a. Public : PascalCase
		b. Protected: camelCase
		c. Internal :  camelCase
		d. Private : _camelCase
	• Example code present in Microsoft's guideline has camelCase for public, protected, internal fields
		○ [https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/protected](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/protected)
		○ Private Field has underscore camelCase
Also, in its Guideline https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names

2023-08-15 17:19 UTC, merged